
import pyautogui, time, os

def append_to_file():
    game_name = input(" Enter the name of the game that you want to added to the website >> ")
    game_path = input("Enter the game path that you want to add to the website >> ")
    photo_name = input(" Enter the path of the photo that you want to added to the game on your website > ")
    print("[01] Fighting games          [02] Shooting games         [03] Action games ")
    print("[04] Arcade games            [05] Sports games           [06] Cards games ")
    print("[07]Dress up games           [08] Free games             [09]Cars games")
    print("[10] Skill games")
    game = int(input("Enter the section >> "))
    if game == 1 or game == "01":
        with open("website/html/fightingGames.html", mode='a') as fighting_file:
            fighting_file.write(f'<div class="{game_name} games"><div class="img"><a href="games/fighting/{game_name}.html"><img src="{photo_name}" class="games-img"><div class="text2 text1"><h4>Fighting Games: {game_name} </h4><p>Launch : 05/22/2021</p></div></a></div>\n')
            with open(f"website/html/games/fighting/{game_name}.html", mode='w') as fighting_game:
                fighting_game.write(f'<!DOCTYPE html><html><head><title>fighting Games</title><link rel="icon" href="../imges/icon.jpg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous"><link rel="preconnect" href="https://fonts.gstatic.com"><link rel="stylesheet" href="../../../main.css"><script src="../../../javascript/main.js"></script><meta charset="utf-8"></head><body><div class="dark-mood"></div><div class="backdrop"></div><header><div class="main-sun"><button class="main-sun__button" onclick="sun()"><span style="font-size: 2rem; color: #fff;" class="main-sun__span"><i class="fas fa-sun"></i></span></button></div><div class="main-moon"><button class="main-moon__button" onclick="moon()"><span style="font-size: 2rem; color: #888;" class="main-moon__span"><i class="fas fa-moon"></i></span></button></div><div class="main-div-h1"><h1 class="main-h1">{game_name}</h1></div></header><div class="DNF-em"><embed src="{game_path}" quality="best" menu="true" width="700" height="500" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" id="main-game" /></div></body>')
                print("done!!")
    elif game == 2 or game == "02":
        with open("website/html/warGames.html", mode='a') as shoting_file:
            shoting_file.write(f'<div class="{game_name} games"><div class="img"><a href="games/fighting/{game_name}.html"><img src="{photo_name}" class="games-img"><div class="text2 text1"><h4>Fighting Games: {game_name} </h4><p>Launch : 05/22/2021</p></div></a></div>\n')
            with open(f"website/html/games/shooting/{game_name}.html", mode='w') as shoting_game:
                shoting_game.write(f'<!DOCTYPE html><html><head><title>fighting Games</title><link rel="icon" href="../imges/icon.jpg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous"><link rel="preconnect" href="https://fonts.gstatic.com"><link rel="stylesheet" href="../../../main.css"><script src="../../../javascript/main.js"></script><meta charset="utf-8"></head><body><div class="dark-mood"></div><div class="backdrop"></div><header><div class="main-sun"><button class="main-sun__button" onclick="sun()"><span style="font-size: 2rem; color: #fff;" class="main-sun__span"><i class="fas fa-sun"></i></span></button></div><div class="main-moon"><button class="main-moon__button" onclick="moon()"><span style="font-size: 2rem; color: #888;" class="main-moon__span"><i class="fas fa-moon"></i></span></button></div><div class="main-div-h1"><h1 class="main-h1">{game_name}</h1></div></header><div class="DNF-em"><embed src="{game_path}" quality="best" menu="true" width="700" height="500" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" id="main-game" /></div></body>')
                print("done!!")
    elif game == 3 or game == "03":
        with open("website/html/ActionGames.html", mode='a') as Action_file:
            Action_file.write(f'<div class="{game_name} games"><div class="img"><a href="games/fighting/{game_name}.html"><img src="{photo_name}" class="games-img"><div class="text2 text1"><h4>Fighting Games: {game_name} </h4><p>Launch : 05/22/2021</p></div></a></div>\n')
            with open(f"website/html/games/Action/{game_name}.html", mode='w') as Action_game:
                Action_game.write(f'<!DOCTYPE html><html><head><title>fighting Games</title><link rel="icon" href="../imges/icon.jpg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous"><link rel="preconnect" href="https://fonts.gstatic.com"><link rel="stylesheet" href="../../../main.css"><script src="../../../javascript/main.js"></script><meta charset="utf-8"></head><body><div class="dark-mood"></div><div class="backdrop"></div><header><div class="main-sun"><button class="main-sun__button" onclick="sun()"><span style="font-size: 2rem; color: #fff;" class="main-sun__span"><i class="fas fa-sun"></i></span></button></div><div class="main-moon"><button class="main-moon__button" onclick="moon()"><span style="font-size: 2rem; color: #888;" class="main-moon__span"><i class="fas fa-moon"></i></span></button></div><div class="main-div-h1"><h1 class="main-h1">{game_name}</h1></div></header><div class="DNF-em"><embed src="{game_path}" quality="best" menu="true" width="700" height="500" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" id="main-game" /></div></body>')
                print("done!!")
    elif game == 4 or game == "04":
        with open("website/html/ArcadeGames.html", mode='a') as arcade_file:
            arcade_file.write(f'<div class="{game_name} games"><div class="img"><a href="games/fighting/{game_name}.html"><img src="{photo_name}" class="games-img"><div class="text2 text1"><h4>Fighting Games: {game_name} </h4><p>Launch : 05/22/2021</p></div></a></div>\n')
            with open(f"website/html/games/arcade/{game_name}.html", mode='w') as arcade_game:
                arcade_game.write(f'<!DOCTYPE html><html><head><title>fighting Games</title><link rel="icon" href="../imges/icon.jpg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous"><link rel="preconnect" href="https://fonts.gstatic.com"><link rel="stylesheet" href="../../../main.css"><script src="../../../javascript/main.js"></script><meta charset="utf-8"></head><body><div class="dark-mood"></div><div class="backdrop"></div><header><div class="main-sun"><button class="main-sun__button" onclick="sun()"><span style="font-size: 2rem; color: #fff;" class="main-sun__span"><i class="fas fa-sun"></i></span></button></div><div class="main-moon"><button class="main-moon__button" onclick="moon()"><span style="font-size: 2rem; color: #888;" class="main-moon__span"><i class="fas fa-moon"></i></span></button></div><div class="main-div-h1"><h1 class="main-h1">{game_name}</h1></div></header><div class="DNF-em"><embed src="{game_path}" quality="best" menu="true" width="700" height="500" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" id="main-game" /></div></body>')
                print("done!!")
    elif game == 5 or game == "05":
        with open("website/html/sportsGames.html", mode='a') as sports_file:
            sports_file.write(f'<div class="{game_name} games"><div class="img"><a href="games/fighting/{game_name}.html"><img src="{photo_name}" class="games-img"><div class="text2 text1"><h4>Fighting Games: {game_name} </h4><p>Launch : 05/22/2021</p></div></a></div>\n')
            with open(f"website/html/games/sports/{game_name}.html", mode='w') as sports_game:
                sports_game.write(f'<!DOCTYPE html><html><head><title>fighting Games</title><link rel="icon" href="../imges/icon.jpg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous"><link rel="preconnect" href="https://fonts.gstatic.com"><link rel="stylesheet" href="../../../main.css"><script src="../../../javascript/main.js"></script><meta charset="utf-8"></head><body><div class="dark-mood"></div><div class="backdrop"></div><header><div class="main-sun"><button class="main-sun__button" onclick="sun()"><span style="font-size: 2rem; color: #fff;" class="main-sun__span"><i class="fas fa-sun"></i></span></button></div><div class="main-moon"><button class="main-moon__button" onclick="moon()"><span style="font-size: 2rem; color: #888;" class="main-moon__span"><i class="fas fa-moon"></i></span></button></div><div class="main-div-h1"><h1 class="main-h1">{game_name}</h1></div></header><div class="DNF-em"><embed src="{game_path}" quality="best" menu="true" width="700" height="500" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" id="main-game" /></div></body>')
                print("done!!")
    elif game == 6 or game == "06":
        with open("website/html/cardsGames.html", mode='a') as cards_file:
            cards_file.write(f'<div class="{game_name} games"><div class="img"><a href="games/fighting/{game_name}.html"><img src="{photo_name}" class="games-img"><div class="text2 text1"><h4>Fighting Games: {game_name} </h4><p>Launch : 05/22/2021</p></div></a></div>\n')
            with open(f"website/html/games/cards/{game_name}.html", mode='w') as cards_game:
                cards_game.write(f'<!DOCTYPE html><html><head><title>fighting Games</title><link rel="icon" href="../imges/icon.jpg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous"><link rel="preconnect" href="https://fonts.gstatic.com"><link rel="stylesheet" href="../../../main.css"><script src="../../../javascript/main.js"></script><meta charset="utf-8"></head><body><div class="dark-mood"></div><div class="backdrop"></div><header><div class="main-sun"><button class="main-sun__button" onclick="sun()"><span style="font-size: 2rem; color: #fff;" class="main-sun__span"><i class="fas fa-sun"></i></span></button></div><div class="main-moon"><button class="main-moon__button" onclick="moon()"><span style="font-size: 2rem; color: #888;" class="main-moon__span"><i class="fas fa-moon"></i></span></button></div><div class="main-div-h1"><h1 class="main-h1">{game_name}</h1></div></header><div class="DNF-em"><embed src="{game_path}" quality="best" menu="true" width="700" height="500" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" id="main-game" /></div></body>')
                print("done!!")
    elif game == 7 or game == "07":
        with open("website/html/DressUpGames.html", mode='a') as DressUp_file:
            DressUp_file.write(f'<div class="{game_name} games"><div class="img"><a href="games/fighting/{game_name}.html"><img src="{photo_name}" class="games-img"><div class="text2 text1"><h4>Fighting Games: {game_name} </h4><p>Launch : 05/22/2021</p></div></a></div>\n')
            with open(f"website/html/games/dressup/{game_name}.html", mode='w') as dressup_game:
                dressup_game.write(f'<!DOCTYPE html><html><head><title>fighting Games</title><link rel="icon" href="../imges/icon.jpg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous"><link rel="preconnect" href="https://fonts.gstatic.com"><link rel="stylesheet" href="../../../main.css"><script src="../../../javascript/main.js"></script><meta charset="utf-8"></head><body><div class="dark-mood"></div><div class="backdrop"></div><header><div class="main-sun"><button class="main-sun__button" onclick="sun()"><span style="font-size: 2rem; color: #fff;" class="main-sun__span"><i class="fas fa-sun"></i></span></button></div><div class="main-moon"><button class="main-moon__button" onclick="moon()"><span style="font-size: 2rem; color: #888;" class="main-moon__span"><i class="fas fa-moon"></i></span></button></div><div class="main-div-h1"><h1 class="main-h1">{game_name}</h1></div></header><div class="DNF-em"><embed src="{game_path}" quality="best" menu="true" width="700" height="500" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" id="main-game" /></div></body>')
                print("done!!")
    elif game == 8 or game == "08":
        with open("website/html/freeGames.html", mode='a') as free_file:
            free_file.write(f'<div class="{game_name} games"><div class="img"><a href="games/fighting/{game_name}.html"><img src="{photo_name}" class="games-img"><div class="text2 text1"><h4>Fighting Games: {game_name} </h4><p>Launch : 05/22/2021</p></div></a></div>\n')
            with open(f"website/html/games/free/{game_name}.html", mode='w') as free_game:
                free_game.write(f'<!DOCTYPE html><html><head><title>fighting Games</title><link rel="icon" href="../imges/icon.jpg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous"><link rel="preconnect" href="https://fonts.gstatic.com"><link rel="stylesheet" href="../../../main.css"><script src="../../../javascript/main.js"></script><meta charset="utf-8"></head><body><div class="dark-mood"></div><div class="backdrop"></div><header><div class="main-sun"><button class="main-sun__button" onclick="sun()"><span style="font-size: 2rem; color: #fff;" class="main-sun__span"><i class="fas fa-sun"></i></span></button></div><div class="main-moon"><button class="main-moon__button" onclick="moon()"><span style="font-size: 2rem; color: #888;" class="main-moon__span"><i class="fas fa-moon"></i></span></button></div><div class="main-div-h1"><h1 class="main-h1">{game_name}</h1></div></header><div class="DNF-em"><embed src="{game_path}" quality="best" menu="true" width="700" height="500" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" id="main-game" /></div></body>')
                print("done!!")
    elif game == 9 or game == "09":
        with open("website/html/carsGames.html", mode='a') as cars_file:
            cars_file.write(f'<div class="{game_name} games"><div class="img"><a href="games/fighting/{game_name}.html"><img src="{photo_name}" class="games-img"><div class="text2 text1"><h4>Fighting Games: {game_name} </h4><p>Launch : 05/22/2021</p></div></a></div>\n')
            with open(f"website/html/games/cars/{game_name}.html", mode='w') as cars_game:
                cars_game.write(f'<!DOCTYPE html><html><head><title>fighting Games</title><link rel="icon" href="../imges/icon.jpg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous"><link rel="preconnect" href="https://fonts.gstatic.com"><link rel="stylesheet" href="../../../main.css"><script src="../../../javascript/main.js"></script><meta charset="utf-8"></head><body><div class="dark-mood"></div><div class="backdrop"></div><header><div class="main-sun"><button class="main-sun__button" onclick="sun()"><span style="font-size: 2rem; color: #fff;" class="main-sun__span"><i class="fas fa-sun"></i></span></button></div><div class="main-moon"><button class="main-moon__button" onclick="moon()"><span style="font-size: 2rem; color: #888;" class="main-moon__span"><i class="fas fa-moon"></i></span></button></div><div class="main-div-h1"><h1 class="main-h1">{game_name}</h1></div></header><div class="DNF-em"><embed src="{game_path}" quality="best" menu="true" width="700" height="500" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" id="main-game" /></div></body>')
    elif game == 10:
        with open("website/html/skillGames.html", mode='a') as skill_file:
            skill_file.write(f'<div class="{game_name} games"><div class="img"><a href="games/fighting/{game_name}.html"><img src="{photo_name}" class="games-img"><div class="text2 text1"><h4>Fighting Games: {game_name} </h4><p>Launch : 05/22/2021</p></div></a></div>\n')
            with open(f"website/html/games/skill/{game_name}.html", mode='w') as skill_game:
                skill_game.write(f'<!DOCTYPE html><html><head><title>fighting Games</title><link rel="icon" href="../imges/icon.jpg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous"><link rel="preconnect" href="https://fonts.gstatic.com"><link rel="stylesheet" href="../../../main.css"><script src="../../../javascript/main.js"></script><meta charset="utf-8"></head><body><div class="dark-mood"></div><div class="backdrop"></div><header><div class="main-sun"><button class="main-sun__button" onclick="sun()"><span style="font-size: 2rem; color: #fff;" class="main-sun__span"><i class="fas fa-sun"></i></span></button></div><div class="main-moon"><button class="main-moon__button" onclick="moon()"><span style="font-size: 2rem; color: #888;" class="main-moon__span"><i class="fas fa-moon"></i></span></button></div><div class="main-div-h1"><h1 class="main-h1">{game_name}</h1></div></header><div class="DNF-em"><embed src="{game_path}" quality="best" menu="true" width="700" height="500" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" id="main-game" /></div></body>')
                print("done!!")

    


append_to_file()